<html>
    <script>

const val1 = 69;
let val2 = 420;
try {
console.log(val2, 'original val');

val2 += 50;
console.log(val2, 'after getting changed');
console.log(val2, 't2');
}
catch (err) {
    console.log(err.message, 'error occurred')
}
finally 
{
    console.log("I'm always executed")
}
</script>
</html>